#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 2 -*-

if [ "$SNAP_ARCH" = "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" = "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

if [ "$HOME" = "$SNAP_USER_DATA" ]; then
  # This is a user command (not a system service).  Let's adjust our HOME
  # back to our real home.
  #export HOME=$(sh <<< "echo ~$USER")
  export HOME=$SNAP_USER_COMMON
else
  export HOME=$SNAP_COMMON
fi

export PATH="$PATH:/snap/bin"

export GST_PLUGIN_SCANNER=$SNAP/usr/lib/$ARCH/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner

# desktop-launch uses SNAP_USER_DATA and HOME differently than us
export SNAP_USER_DATA=$HOME

exec $SNAP/bin/desktop-launch "$@"
